---
excludes:
  scopes:
    - pattern: "checkstyle"
      reason: "BUILD_DEPENDENCY_OF"
      comment: "Packages for code styling checks (testing) only."

    - pattern: "devDependencies"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only."

    - pattern: "jacocoAgent"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Packages for code coverage (testing) only."

    - pattern: "jacocoAnt"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Packages for code coverage (testing) only."

    - pattern: "test.*"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Packages for testing only."

    - pattern: "annotationProcessor"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only."

    - pattern: "compileClasspath"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only."

    - pattern: "compileOnly"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only."

  paths:
    - pattern: "web-app/3RD-PARTY-NOTICES.txt"
      reason: "DOCUMENTATION_OF"
      comment: "3rd party notices."

    - pattern: "packages/**"
      reason: "BUILD_TOOL_OF"
      comment: "Build scripts."

    - pattern: "gradle/**"
      reason: "BUILD_TOOL_OF"
      comment: "Build tools."

    - pattern: "docker-dev/**"
      reason: "BUILD_TOOL_OF"
      comment: "Development tools."

    - pattern: "docs/**"
      reason: "DOCUMENTATION_OF"
      comment: "Documentation."

curations:
  packages:
  - id: "Maven:commons-cli:commons-cli:1.2"
    curations:
      comment: "ORT clones too much content from this specific Subversion VCS, so prefer the source artifact."
      source_code_origins: [ARTIFACT, VCS]
  - id: "Maven:commons-cli:commons-cli:1.4"
    curations:
      comment: "ORT clones too much content from this specific Subversion VCS, so prefer the source artifact."
      source_code_origins: [ARTIFACT, VCS]
  - id: "Maven:commons-codec:commons-codec:1.4"
    curations:
      comment: "ORT clones too much content from this specific Subversion VCS, so prefer the source artifact."
      source_code_origins: [ARTIFACT, VCS]
  - id: "Maven:commons-codec:commons-codec:1.15"
    curations:
      comment: "The Git URL looks malformed, so prefer the source artifact."
      source_code_origins: [ARTIFACT, VCS]
  - id: "Maven:commons-configuration:commons-configuration:1.10"
    curations:
      comment: "ORT clones too much content from this specific Subversion VCS, so prefer the source artifact."
      source_code_origins: [ARTIFACT, VCS]
  - id: "Maven:commons-io:commons-io:2.4"
    curations:
      comment: "ORT clones too much content from this specific Subversion VCS, so prefer the source artifact."
      source_code_origins: [ARTIFACT, VCS]
  - id: "Maven:commons-lang:commons-lang:2.6"
    curations:
      comment: "ORT clones too much content from this specific Subversion VCS, so prefer the source artifact."
      source_code_origins: [ARTIFACT, VCS]
  - id: "Maven:commons-logging:commons-logging:1.2"
    curations:
      comment: "ORT clones too much content from this specific Subversion VCS, so prefer the source artifact."
      source_code_origins: [ARTIFACT, VCS]
  - id: "Maven:javax.servlet:javax.servlet-api:3.1.0"
    curations:
      comment: "ORT clones too much content from this specific Subversion VCS, so prefer the source artifact."
      source_code_origins: [ARTIFACT, VCS]
  - id: "Maven:log4j:log4j:1.2.16"
    curations:
      comment: "ORT clones too much content from this specific Subversion VCS, so prefer the source artifact."
      source_code_origins: [ARTIFACT, VCS]
  - id: "Maven:net.sf.saxon:Saxon-HE:9.5.1-8"
    curations:
      comment: "ORT clones too much content from this specific Subversion VCS, so prefer the source artifact."
      source_code_origins: [ARTIFACT, VCS]
  - id: "Maven:net.sourceforge.htmlcleaner:htmlcleaner:2.24"
    curations:
      comment: "ORT clones too much content from this specific Subversion VCS, so prefer the source artifact."
      source_code_origins: [ARTIFACT, VCS]
  - id: "Maven:org.apache.pdfbox:fontbox:2.0.20"
    curations:
      comment: "ORT clones too much content from this specific Subversion VCS, so prefer the source artifact."
      source_code_origins: [ARTIFACT, VCS]
  - id: "Maven:org.apache.pdfbox:pdfbox:2.0.20"
    curations:
      comment: "ORT clones too much content from this specific Subversion VCS, so prefer the source artifact."
      source_code_origins: [ARTIFACT, VCS]
  - id: "Maven:org.apache.santuario:xmlsec:2.1.5"
    curations:
      comment: "ORT clones too much content from this specific Subversion VCS, so prefer the source artifact."
      source_code_origins: [ARTIFACT, VCS]
  - id: "Maven:xml-apis:xml-apis:1.0.b2"
    curations:
      comment: "ORT clones too much content from this specific Subversion VCS, so prefer the source artifact."
      source_code_origins: [ARTIFACT, VCS]

license_choices:
  repository_license_choices:
    - given: "GPL-2.0-only OR Apache-2.0"
      choice: "Apache-2.0"
    - given: "GPL-2.0-only OR CDDL-1.1"
      choice: "CDDL-1.1"
    - given: "Apache-2.0 OR GPL-2.0-only OR LGPL-2.1-only"
      choice: "Apache-2.0"
    - given: "Apache-2.0 OR GPL-2.0-only"
      choice: "Apache-2.0"
    - given: "Apache-2.0 OR GPL-2.0-only OR LGPL-2.1-only OR LicenseRef-scancode-ldap-sdk-free-use"
      choice: "Apache-2.0"
    - given: "AFL-2.1 OR BSD-3-Clause"
      choice: "BSD-3-Clause"

resolutions:
  rule_violations:
    - message: "copyleft-strong license CC-BY-SA-3.0 in Maven:org.freemarker:freemarker:2.3.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The files meant by this license hit are fonts and therefore use is compliant."
    - message: "free-restricted license LicenseRef-scancode-adobe-postscript in Maven:com.github.librepdf:openpdf:1.3.*"
      reason: "NOT_MODIFIED_EXCEPTION"
      comment: "The LicenseRef-scancode-adobe-postscript license allows redistributing without modifications. As long as the files licensed with the said license are satisfied."
    - message: "property:non-commercial license CC-BY-NC-SA-2.0 in Maven:org.xhtmlrenderer:flying-saucer-core:9.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "The graphic files flying-saucer-examples/nomaven/svg/resources/svg/dat/face-crying.svg and flying-saucer-examples/nomaven/svg/resources/svg/dat/face-sad.svg in this dependency may not be used."
    - message: "free-restricted license CC-BY-NC-SA-2.0 in Maven:org.xhtmlrenderer:flying-saucer-core:9.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "The graphic files flying-saucer-examples/nomaven/svg/resources/svg/dat/face-crying.svg and flying-saucer-examples/nomaven/svg/resources/svg/dat/face-sad.svg in this dependency may not be used."
    - message: "free-restricted license LicenseRef-scancode-w3c-docs-20021231 in Maven:org.xhtmlrenderer:flying-saucer-core:9.1.*"
      reason: "NOT_MODIFIED_EXCEPTION"
      comment: "This documentation file can not be modified."
    - message: "free-restricted license LicenseRef-scancode-w3c-docs-20021231 in Maven:org.xhtmlrenderer:flying-saucer-pdf-openpdf:9.1.*"
      reason: "NOT_MODIFIED_EXCEPTION"
      comment: "This documentation file can not be modified."
    - message: "copyleft-strong license GPL-2.0-only in Maven:com.unboundid:unboundid-ldapsdk:5.1.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "This is a license choice, allowing choosing Apache-2.9, and the resolution is used since the license choice functionality does not work."
    - message: "proprietary-free license TMate in Maven:com.unboundid:unboundid-ldapsdk:5.1.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "This license relates to an extra of the dependency, svnkit, which is not used. Therefore the license is complied with."
    - message: "property:network-clause license AGPL-3.0-only in Maven:org.xhtmlrenderer:flying-saucer-core:9.1.*"
      reason: "NOT_MODIFIED_EXCEPTION"
      comment: "This license relates to a pdf-generation of a a dependency of a dependency. It, and the application that uses it, is not used, and not modified, and therefore the license is complied with without additional tasks."
    - message: "property:advertising-clause license LicenseRef-scancode-rsa-md4 in Gradle:misp2:web-app:2.9.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "web-app 2.9. contains the file web-app/libs/iaikPkcs11Wrapper.jar whici is licensed under LicenseRef-scancode-rsa-md4 containing an advertising-clause, which must be followed in case the file is used: If the software is used or copied it must be identified as RSA Data Security, Inc. MD4 Message-Digest Algorithm in all material mentioning or referencing this software or this function. Mofications have further requirements."
    - message: "property:advertising-clause license LicenseRef-scancode-rsa-md4 in Gradle::misp2:."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "web-app contains the file web-app/libs/iaikPkcs11Wrapper.jar whici is licensed under LicenseRef-scancode-rsa-md4 containing an advertising-clause, which must be followed in case the file is used: If the software is used or copied it must be identified as RSA Data Security, Inc. MD4 Message-Digest Algorithm in all material mentioning or referencing this software or this function. Mofications have further requirements."
    - message: "property:advertising-clause license OpenSSL in Maven:org.apache.santuario:xmlsec:2.1.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "For OpenSSL toolkit, the following advertising-clause, which must be followed in case the toolkit is used: All advertising materials mentioning features or use of this software must display the following acknowledgment: 'This product includes software developed by the OpenSSL Project for use in the OpenSSL Toolkit. (http://www.openssl.org/)' and All advertising materials mentioning features or use of this software must display the following acknowledgement: 'This product includes cryptographic software written by Eric Young (eay@cryptsoft.com)' The word 'cryptographic' can be left out if the routines from the library being used are not cryptographic related :-)."
    - message: "commercial license LicenseRef-scancode-proprietary-license in Gradle:misp2:web-app:2.9.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "These are false positives that are found from the project itself, therefore the findings are not fetched from configuration provider."
    - message: "commercial license LicenseRef-scancode-proprietary-license in NPM::orbeon-forms:2016.3.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "These are likely oudated references to old licensing scheme, see https://github.com/orbeon/orbeon-forms/issues/6354 for possible fix."
    - message: "commercial license LicenseRef-scancode-proprietary-license in Gradle::misp2.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "These are false positives that are found from the project itself, therefore the findings are not fetched from configuration provdider."
    - message: "commercial license LicenseRef-scancode-proprietary-license in Maven:com.sun.xml.ws:policy:2.7.*"
      reason: "NOT_MODIFIED_EXCEPTION"
      comment: "This license relates to a third party content, under undefined OASIS-licenses, as per the META-INF/NOTICE.md file. However, the files are not in the package and therefore no license is needed."
    - message: "commercial license LicenseRef-scancode-proprietary-license in Maven:org.jvnet.mimepull:mimepull:1.9.*"
      reason: "NOT_MODIFIED_EXCEPTION"
      comment: "This license relates to a third party content, under undefined OASIS-licenses, as per the META-INF/NOTICE.md file. However, the files are not in the package and therefore no license is needed."
