---
excludes:
  scopes:
  - pattern: "checkstyle"
    reason: "BUILD_DEPENDENCY_OF"
    comment: "Packages for code styling checks (testing) only."

  - pattern: "devDependencies"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "jacocoAgent"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for code coverage (testing) only."

  - pattern: "jacocoAnt"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for code coverage (testing) only."

  - pattern: "test.*"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for testing only."

  - pattern: "annotationProcessor"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "compileClasspath"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "compileOnly"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  paths:
  - pattern: "web-app/3RD-PARTY-NOTICES.txt"
    reason: "DOCUMENTATION_OF"
    comment: "3rd party notices."

  - pattern: "packages/**"
    reason: "BUILD_TOOL_OF"
    comment: "Build scripts."

  - pattern: "gradle/**"
    reason: "BUILD_TOOL_OF"
    comment: "Build tools."

  - pattern: "docker-dev/**"
    reason: "BUILD_TOOL_OF"
    comment: "Development tools."

  - pattern: "docs/**"
    reason: "DOCUMENTATION_OF"
    comment: "Documentation."

license_choices:
  repository_license_choices:
  - given: "GPL-2.0-only OR Apache-2.0"
    choice: "Apache-2.0"
  - given: "GPL-2.0-only OR CDDL-1.1"
    choice: "CDDL-1.1"
  - given: "Apache-2.0 OR GPL-2.0-only OR LGPL-2.1-only"
    choice: "Apache-2.0"
  - given: "Apache-2.0 OR GPL-2.0-only"
    choice: "Apache-2.0"

resolutions:
  rule_violations:
    - message: "copyleft-strong license CC-BY-SA-3.0 in Maven:org.freemarker:freemarker:2.3.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The files meant by this license hit are fonts and therefore use is compliant."
    - message: "free-restricted license LicenseRef-scancode-adobe-postscript in Maven:com.github.librepdf:openpdf:1.3.*"
      reason: "NOT_MODIFIED_EXCEPTION"
      comment: "The LicenseRef-scancode-adobe-postscript license allows redistributing without modifications. As long as the files licensed with the said license are satisfied."
    - message: "property:non-commercial license CC-BY-NC-SA-2.0 in Maven:org.xhtmlrenderer:flying-saucer-core:9.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "The graphic files flying-saucer-examples/nomaven/svg/resources/svg/dat/face-crying.svg and flying-saucer-examples/nomaven/svg/resources/svg/dat/face-sad.svg in this dependency may not be used."
    - message: "free-restricted license CC-BY-NC-SA-2.0 in Maven:org.xhtmlrenderer:flying-saucer-core:9.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "The graphic files flying-saucer-examples/nomaven/svg/resources/svg/dat/face-crying.svg and flying-saucer-examples/nomaven/svg/resources/svg/dat/face-sad.svg in this dependency may not be used."
    - message: "free-restricted license LicenseRef-scancode-w3c-docs-20021231 in Maven:org.xhtmlrenderer:flying-saucer-core:9.1.*"
      reason: "NOT_MODIFIED_EXCEPTION"
      comment: "This documentation file can not be modified."
    - message: "free-restricted license LicenseRef-scancode-w3c-docs-20021231 in Maven:org.xhtmlrenderer:flying-saucer-pdf-openpdf:9.1.*"
      reason: "NOT_MODIFIED_EXCEPTION"
      comment: "This documentation file can not be modified."
